//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "matchy_meetup_pair")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub round_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::matchy_meetup_pair_member::Entity")]
    MatchyMeetupPairMember,
    #[sea_orm(
        belongs_to = "super::matchy_meetup_round::Entity",
        from = "Column::RoundId",
        to = "super::matchy_meetup_round::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MatchyMeetupRound,
}

impl Related<super::matchy_meetup_pair_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchyMeetupPairMember.def()
    }
}

impl Related<super::matchy_meetup_round::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchyMeetupRound.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
