//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "matchy_meetup_round")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::matchy_meetup_pair::Entity")]
    MatchyMeetupPair,
}

impl Related<super::matchy_meetup_pair::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MatchyMeetupPair.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
