//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod matchy_meetup_opt_in;
pub mod matchy_meetup_pair;
pub mod matchy_meetup_pair_member;
pub mod matchy_meetup_round;
pub mod server_calendar;
pub mod server_event;
pub mod snipe_opt_out;
pub mod spotting_message;
pub mod spotting_victim;
pub mod user_stat;
