//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub mod prelude;

pub mod matchy_meetup_opt_in;
pub mod matchy_meetup_pair;
pub mod matchy_meetup_pair_member;
pub mod matchy_meetup_round;
pub mod message;
pub mod opt_out;
pub mod server_calendar;
pub mod server_event;
pub mod snipe;
pub mod user_stat;
