//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "server_calendar")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub calendar_id: String,
    #[sea_orm(column_type = "Text")]
    pub calendar_name: String,
    #[sea_orm(column_type = "Text")]
    pub webhook_id: String,
    #[sea_orm(column_type = "Text")]
    pub access_token: String,
    pub access_expires: DateTime,
    #[sea_orm(column_type = "Text")]
    pub refresh_token: String,
    pub webhook_last_updated: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::server_event::Entity")]
    ServerEvent,
}

impl Related<super::server_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerEvent.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
