//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "server_event")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: i64,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub calendar_id: String,
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub calendar_event_id: String,
    pub guild_event_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::server_calendar::Entity",
        from = "(Column::GuildId, Column::CalendarId)",
        to = "(super::server_calendar::Column::GuildId, super::server_calendar::Column::CalendarId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ServerCalendar,
}

impl Related<super::server_calendar::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerCalendar.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
